### ISSUE TITLE
Transport.RoundTrip does not respect the contract of the RoundTripper interface

### ISSUE THREAD

**Issue by lobre** [bradleyfalzon/ghinstallation#20]
Hello,

Here are some chunks of what is stated in `go doc http.RoundTripper`.

```
A RoundTripper must be safe for concurrent use by multiple goroutines.

RoundTrip should not modify the request, except for
consuming and closing the Request's Body. RoundTrip may
read fields of the request in a separate goroutine.

RoundTrip must always close the body, including on errors,
but depending on the implementation may do so in a separate
goroutine even after RoundTrip returns.
```

In the current implementation, the original request is modified.

https://github.com/bradleyfalzon/ghinstallation/blob/master/transport.go#L92

As well, if `t.Token()` fails, we should ensure the `req.Body` is properly closed before returning.

https://github.com/bradleyfalzon/ghinstallation/blob/master/transport.go#L87

Some ideas to make this code compliant to the interface can be found in the following package.

https://github.com/golang/oauth2/blob/master/transport.go

You can notice the `req.Body` is closed anyway and the original request is cloned before being modified.

Loric

**Comment by akavel** [comment]
Updating the links above to the current code, `go run -race` on a sample app shows a race between e.g.:

https://github.com/bradleyfalzon/ghinstallation/blob/81f7095e75089d688962bb75ba9814748d90f004/transport.go#L88

and

https://github.com/bradleyfalzon/ghinstallation/blob/81f7095e75089d688962bb75ba9814748d90f004/transport.go#L164
