### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/ghinstallation#32]
The latest tag release was v0.1.2, since then there's been two breaking changes.

1. d37c8f22c4ff4284af47f91a8428e6be28b7619a added a context to Transport.Token, this was exported, but unlikely to be used by most use cases. See #21 
1. 344ce85a8335355569c30a110000be4668cfa34a changed the AppID type from `int` to `int64` to follow go-github's convention. See #27.

If you were using some dependency management tools, it's likely you pinned to the tagged releases, and weren't affected by the two above breaking changes.

Now this API has settled a bit, and we've introduced Go Modules support in #28, I think it's time to release v1.0.0.

From my understanding of Go Modules, it should just be a matter of pushing the tag v1.0.0 to the latest commit. I.e. we shouldn't need to change go.mod to list the new version like we would if we were to release v2.0.0 (changing the module name to `github.com/bradleyfalzon/ghinstallation/v2`). Further, no changes to the `README.md` file should be required as the `go get` syntax for users who haven't yet used ghinstallation will get the latest tagged release.

@wlynch do you have any comments on this? Is this understanding correct?

**Comment by wlynch** [comment]
Yup! This LGTM. :+1:

**Comment by donatj** [comment]
You should also change installation id to int64 as it is in the new Google GitHub SDK

https://github.com/google/go-github/blob/master/github/apps.go#L86

**Comment by wlynch** [comment]
@donatj 344ce85a8335355569c30a110000be4668cfa34a changed both App and Installation ID to int64, so we should be good to go.

**Comment by bradleyfalzon** [comment]
I'll push 1.0.0 now then

**Comment by bradleyfalzon** [comment]
Doneski! Thanks all!

https://github.com/bradleyfalzon/ghinstallation/releases/tag/v1.0.0
