### ISSUE TITLE
dgrijalva/jwt-go is deprecated and golang-jwt/jwt should be used

### ISSUE THREAD

**Issue by SVilgelm** [bradleyfalzon/ghinstallation#54]
Could you please replace https://github.com/dgrijalva/jwt-go with https://github.com/golang-jwt/jwt since the `dgrijalva/jwt-go` is deprecated and `golang-jwt/jwt` is a community fork?

**Comment by bradleyfalzon** [comment]
Yeah, could we iterate on #53 for this?

**Comment by SVilgelm** [comment]
Oh, sorry, didn't see that PR

**Comment by SVilgelm** [comment]
fixed
