### ISSUE TITLE
Provide a transport that allows authenticating against the App-level endpoints

### ISSUE THREAD

**Issue by itay** [bradleyfalzon/ghinstallation#6]
Per the GitHub [docs](https://developer.github.com/apps/building-integrations/setting-up-and-registering-github-apps/about-authentication-options-for-github-apps/#jwt-payload), there are some endpoints that are only available when authenticating as an app, as opposed to authenticating as an installation (specifically, the `/app` and `/app/installations` endpoints). It would be nice if the library had a way to create a client that would authenticate using that JWT token.

Fortunately, most of the code is already there - it's basically just constructing the bearer token and adding it to the `Authorization` header. It simply needs a different transport implementation. I started prototyping this, but realized it would end up duplicating the code, and thought I'd open an issue to see if you had a preferred way of doing it. Should be a pretty easy addition.

**Comment by bradleyfalzon** [comment]
Yeah I’ve always had a thought that I should have split this transport into its two components, integration (apps) transport and installation transport.

If I provided another transport AppsTranport which also implemented http.RoundTripper - does that API sound OK to you?

**Comment by bradleyfalzon** [comment]
OK, merged #7 let me know once you've confirmed it again and I'll tag a new release.

**Comment by itay** [comment]
OK - pulled the latest, made sure it was building right, and my local tests are all good with it. Ship it!

**Comment by bradleyfalzon** [comment]
Thanks @itay for this issue and review comments, I've pushed a new tag v0.1.2.
