### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by pwntester** [bradleyfalzon/ghinstallation#76]
Hi,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in GHInstallation. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me (@pwntester) in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Thanks!

**Comment by bradleyfalzon** [comment]
Feel free to post more information in the draft sec advisory so we can understand

**Comment by pwntester** [comment]
Thanks!
