### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by elgohr** [bradleyfalzon/ghinstallation#84]
Hi, is this repository still maintained?
Seeing a few PRs & issues waiting for comments/merges for multiple months.

**Comment by bradleyfalzon** [comment]
Yeah but @wlynch often does a better job than I do.

**Comment by elgohr** [comment]
👍

**Comment by AndrewGutierrezCastro** [comment]
**Hey @bradleyfalzon, would you be open to a few contributions?**

Do you have a pull request template or any contribution guidelines for adding new features?

One improvement I'd love to add is support for loading credentials from environment variables. It seems like a useful and secure addition.

Are there any other safety- or security-related improvements you'd be interested in? I'd also like to help by tackling a few Dependabot pull requests from time to time to keep the project up to date and secure.

Thanks for sharing and maintaining this library @wlynch!
