### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Philmod** [bradleyfalzon/ghinstallation#9]
Hey Bradley,

We would love to use your package at Google, but we can't because of the "public domain" license.

Would you consider changing the license? (Apache-2.0 is prefered, but others are fine)

I'm happy to create the PR.

Best,
Philippe

**Comment by ScottMansfield** [comment]
are your requirements strictly to have one specific license or a set of licenses?

**Comment by Philmod** [comment]
I don't think it makes sense to have multiple licenses

**Comment by ScottMansfield** [comment]
I don't think it makes sense to require a more restrictive license for you to use it.

More specifically: what are your requirements on licenses? Are you required to have Apache-2.0? What's the set of licenses allowed?

**Comment by Philmod** [comment]
This is not needed anymore. Sorry for bothering.
