### ISSUE TITLE
BaseURL should not be hardcoded

### ISSUE THREAD

**Issue by Kitanotori** [bradleyfalzon/ghinstallation#90]
### Problem
Hardcoding of apiBaseURL in https://github.com/bradleyfalzon/ghinstallation/blob/master/appsTransport.go#L57, breaks e.g. Argo Events auth (https://github.com/argoproj/argo-events/issues/2494) in case of GitHub Enterprise, when base URL is different from public GitHub. 

### Solution
It should be possible to pass BaseURL as parameter.

**Comment by bradleyfalzon** [comment]
After you new it, you can overwrite it.

See README: https://github.com/bradleyfalzon/ghinstallation#github-enterprise-example

**Comment by Kitanotori** [comment]
It would be helpful if BaseURL could be passed as parameter.

I'd like to do be able to do this:
```
ghinstallation.New(tr, appId, instId, privKeyBytes, baseUrlStr)
```

**Comment by Kitanotori** [comment]
Just in case there's interest in improving the API for GitHub Enterprise compatibility, submitted PR.

**Comment by bradleyfalzon** [comment]
The main reason it's not in the signature is that I've assumed majority of the use cases don't need to customise it, and therefore defaulting to non enterprise made the most sense.

Unfortunately, we can't change the signature now, and I'm still not certain whether I would.

The best I could say would be that I feel the following feels less cumbersome, although it's more verbose, I think it's easier to read. This assumes that t.BaseURL isn't always set, if it was always set then you could remove this conditional and it feels fine.

```go
tr, err := ghinstallation.New(t.transport(), t.AppID, t.InstallationID, []byte(t.PrivateKey))
if err != nil {
    return nil, err
}
if t.BaseURL != "" {
    tr.BaseURL = t.BaseURL
}
return tr, nil 
```

**Comment by Kitanotori** [comment]
@bradleyfalzon The above doesn't work. Problem seems to be that baseURL that is set in Transport is not applied.
```
	return &Transport{
		BaseURL:        atr.BaseURL, // change to this is apparently not reflected to refreshToken logic
		Client:         &http.Client{Transport: atr.tr},
		tr:             atr.tr,
		appID:          atr.appID,
		installationID: installationID,
		appsTransport:  atr,
		mu:             &sync.Mutex{},
	}
```
If the above issue can be fixed, being able to simply change BaseURL is acceptable, but current usage for GitHub Enterprise feels odd - having to basically create the transport twice.

**Comment by Kitanotori** [comment]
Double checked. The above does indeed work. Apparently had issue elsewhere in the code. Function for passing baseURL directly would still be nice to have, though.
