### ISSUE TITLE
Incomplete update to use go-github v50

### ISSUE THREAD

**Issue by Marakai** [bradleyfalzon/ghinstallation#92]
Unfortunately the current release is still 2.1.0 and has not been updated since the change to use go-github v50. As a result I still end up with v45 pulled in. Unless I want to build ghinstallation from source.

**Comment by bradleyfalzon** [comment]
Apologies @Marakai I've merged in the latest v50 references and tagged release https://github.com/bradleyfalzon/ghinstallation/releases/tag/v2.2.0

**Comment by Marakai** [comment]
thank you, that should clean up our go.mod a bit :)
