### ISSUE TITLE
302 Found

### ISSUE THREAD

**Issue by phylake** [bradleyfalzon/ghinstallation#98]
I'm hitting this error message https://github.com/bradleyfalzon/ghinstallation/blob/97b6ed0a80df9265c739660d7f35551ff0276b75/transport.go#L226
where `resp.Status` is `302 Found`

Shouldn't this redirect have been followed?

**Comment by bradleyfalzon** [comment]
Yeah with the default client, it should follow 10 redirects https://pkg.go.dev/net/http#Client, and if this fails should return an error https://cs.opensource.google/go/go/+/refs/tags/go1.20.3:src/net/http/client.go;l=804

Is your client overwriting this behaviour? If there's more than 10 redirects, we should have checked and returned that error.

**Comment by phylake** [comment]
No it shouldn't be. I have roughly this
```golang
import (
	"net/http"
	"github.com/bradleyfalzon/ghinstallation/v2"
	"github.com/google/go-github/v50/github"
)

const (
	GHEUrl = "my GitHub enterprise endpoint"
	ClientId = 1
	InstallationId = 2
	PKPath = "/path/to/app-private-key.pem"
)

func main() {
	transport, _ := ghinstallation.NewKeyFromFile(http.DefaultTransport, ClientId, InstallationId, PKPath)
	transport.BaseURL = GHEUrl

	httpClient := &http.Client{
		Transport: transport,
	}

	ghClient, _ := github.NewEnterpriseClient(GHEUrl, GHEUrl, httpClient)
	
	// ...
}
```

**Comment by phylake** [comment]
Oh it's a redirect to `/login?return_to=...`

**Comment by phylake** [comment]
I needed to append `/api/v3`. I didn't because the go-github docs said it would be appended
https://pkg.go.dev/github.com/google/go-github/v50/github#NewEnterpriseClient
